#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : performance
Version  : 0.6.1
Release  : 16
URL      : https://github.com/python/performance/archive/0.6.1.tar.gz
Source0  : https://github.com/python/performance/archive/0.6.1.tar.gz
Summary  : High-Performance library for Data Structures manipulation
Group    : Development/Tools
License  : MIT
Requires: performance-bin = %{version}-%{release}
Requires: performance-license = %{version}-%{release}
Requires: performance-python = %{version}-%{release}
Requires: performance-python3 = %{version}-%{release}
Requires: Django
Requires: Mako
Requires: MarkupSafe
Requires: SQLAlchemy
Requires: certifi
Requires: docutils
Requires: dulwich
Requires: html5lib
Requires: mercurial
Requires: mpmath
Requires: pathlib2
Requires: pip
Requires: psutil
Requires: pyaes
Requires: setuptools
Requires: singledispatch
Requires: six
Requires: sympy
Requires: tornado
Requires: webencodings
Requires: wheel
BuildRequires : Django
BuildRequires : Mako
BuildRequires : MarkupSafe
BuildRequires : SQLAlchemy
BuildRequires : buildreq-distutils3
BuildRequires : certifi
BuildRequires : docutils
BuildRequires : dulwich
BuildRequires : html5lib
BuildRequires : mercurial
BuildRequires : mpmath
BuildRequires : pathlib2
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : psutil
BuildRequires : py-python
BuildRequires : pyaes
BuildRequires : pytest
BuildRequires : setuptools
BuildRequires : singledispatch
BuildRequires : six
BuildRequires : sympy
BuildRequires : tornado
BuildRequires : tox
BuildRequires : virtualenv
BuildRequires : webencodings
BuildRequires : wheel
Patch1: fix_venv_create_failing_pip10.patch
Patch2: Fix-inside-venv.patch

%description
##########################
The Python Benchmark Suite
##########################

%package bin
Summary: bin components for the performance package.
Group: Binaries
Requires: performance-license = %{version}-%{release}

%description bin
bin components for the performance package.


%package license
Summary: license components for the performance package.
Group: Default

%description license
license components for the performance package.


%package python
Summary: python components for the performance package.
Group: Default
Requires: performance-python3 = %{version}-%{release}

%description python
python components for the performance package.


%package python3
Summary: python3 components for the performance package.
Group: Default
Requires: python3-core

%description python3
python3 components for the performance package.


%prep
%setup -q -n pyperformance-0.6.1
cd %{_builddir}/pyperformance-0.6.1
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583201756
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/performance
cp %{_builddir}/pyperformance-0.6.1/COPYING %{buildroot}/usr/share/package-licenses/performance/8d7eb7ca3a8f0f7125ff91b4517cf42602cb0573
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pyperformance

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/performance/8d7eb7ca3a8f0f7125ff91b4517cf42602cb0573

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
