#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : performance
Version  : 0.6.1
Release  : 8
URL      : https://github.com/python/performance/archive/0.6.1.tar.gz
Source0  : https://github.com/python/performance/archive/0.6.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: performance-bin
Requires: performance-python3
Requires: performance-license
Requires: performance-python
Requires: Django
Requires: Genshi
Requires: Mako
Requires: MarkupSafe
Requires: SQLAlchemy
Requires: certifi
Requires: docutils
Requires: genshic
Requires: html5lib
Requires: mpmath
Requires: pip
Requires: psutil
Requires: pyaes
Requires: setuptools
Requires: six
Requires: sympy
Requires: tornado
Requires: webencodings
Requires: wheel
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv
Patch1: fix_venv_create_failing_pip10.patch
Patch2: Fix-inside-venv.patch

%description
##########################
The Python Benchmark Suite
##########################

%package bin
Summary: bin components for the performance package.
Group: Binaries
Requires: performance-license

%description bin
bin components for the performance package.


%package license
Summary: license components for the performance package.
Group: Default

%description license
license components for the performance package.


%package python
Summary: python components for the performance package.
Group: Default
Requires: performance-python3

%description python
python components for the performance package.


%package python3
Summary: python3 components for the performance package.
Group: Default
Requires: python3-core

%description python3
python3 components for the performance package.


%prep
%setup -q -n performance-0.6.1
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532568786
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/performance
cp COPYING %{buildroot}/usr/share/doc/performance/COPYING
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pyperformance

%files license
%defattr(-,root,root,-)
/usr/share/doc/performance/COPYING

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
